### ISSUE TITLE
Onboarding Security Account fails if CT/AFT are deployed in region different from us-east-1 (single-region-basic)

### ISSUE THREAD

**Issue by omni1504** [awslabs/aft-blueprints#14]
Pipeline fails with:

```
Error: Attempt to index null value
  on main.tf line 91, in module "securityhub_default_policy":
  91:   association_targets = [data.aws_organizations_organization.org.roots[0].id]
    ├────────────────
    │ data.aws_organizations_organization.org.roots is null
This value is null, so it does not have any indices.
```
Cannot see a fix yet or a root cause - the different is that in my case I use us-west-2 (e.g. had to change Security Standards ARNs).

Regards, Amir (AWS)

**Comment by Marcos-Jordao** [comment]
Hello @omni1504 , this issue was resolved now. Please, see the last version on main branch. This issue is explained on issue #17 .
